//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Extranal_Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFood
    {
        public int id { get; set; }
        public string name { get; set; }
        public string cuisine { get; set; }
        public decimal price { get; set; }
        public int quantity { get; set; }
        public bool spicy { get; set; }
    }
}
